class locator(object):
    vacancies = "//body/div[@id='app']/div[1]/div[6]/div[1]/h2[1]"
    qa_engineer = "//body[1]/div[2]/div[1]/div[6]/div[2]/div[2]"
    button_apply = "//button[contains(text(),'Apply Now')]"
    # inside form apply
    form_apply = "//body/div[@id='app']/div[1]/div[2]/div[2]/div[1]/form[1]"
    input_name = "//input[@id='name']"
    input_email = "//input[@id='email']"
    notif_invalid_email = "//span[contains(text(),'Please input the correct email format.')]"
    input_code = "//input[@id='code']"
    info_code = "//span[@id='country']"
    input_phone = "//input[@id='phone']"
    button_next = "//div[contains(text(),'Next')]"
    input_cv = "//input[@id='fileInput']"
    cv_uploaded = "//span[contains(text(),'Complete')]"
    file_too_large = "//span[contains(text(),'File too large')]"
    input_cover_letter = "//textarea[@id='additionalMessage']"
    button_submit = "//div[contains(text(),'Submit')]"
    notif_not_upload_files = "//div[contains(text(),'You haven't uploaded any files')]"
    notif_application_sent = "//div[contains(text(),'Your application for QA Engineer has been sent!')]"
    notif_file_too_large = "//span[contains(text(),'File too large')]"
