name: Python Package

on:
  push:
    branches: [ main ]  # Ganti dengan nama cabang yang sesuai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install

    - name: Run Behave tests
      run: |
        behave features/ --no-capture --format=json > results.json
        allure generate results.json -o allure_report --clean

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-results